### PR TITLE
Just added my info

### PR DESCRIPTION
**Pull request by panoskam**

### CODE REVIEW

**Comment by stdi** [comment]
Commit messages should use verbs in present tense

**Comment by NikosAndreadakis** [comment]
Nice job. Add your name also and merge after

**Review by stdi — CHANGES_REQUESTED** [review]
Commit messages should use verbs in present tense. Please

So, in this case it could become `Update README.md: Add my info` or `Add my info in README.md` etc. You can use `git commit --ammend` in order to fix your commit message, the merge conflicts due to the previous merges can be resolved later.

**Review by stdi — APPROVED** [review]
Thanks!

**Pull request merged**
