### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stdi**
Add Table of Contents section.

### CODE REVIEW

**Comment by NikosAndreadakis** [comment]
Nice job. Add your info also and then merge.

**Review by ghost — APPROVED** [review]
Looks great.

**Comment by gsopy** [comment]
Great

**Review by Katethoma — COMMENTED** [review]
perfect

**Comment by kiriakikar** [comment]
great!!!

**Comment by vkaragia** [comment]
great!

**Pull request merged**
